name: validate-conventional-commits

on: [push]

jobs:
  check:
    uses: wittdennis/pipelines/.github/workflows/cog-validate.yaml@f53702a770636f128cf8cc831a681c45b0b3470d # 2.0.62
    with:
      check-latest-tag-only: false
