name: github-release

on:
  workflow_dispatch:

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@b65917377ef7ceeeb30ee3ec2a42135d403ca822 # 2.0.59
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
