name: github-release

on:
  workflow_dispatch:

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@fb06128e939b3c347883b4a369d4bba39011ce0b # 2.0.60
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
