name: github-release

on:
  workflow_dispatch:

jobs:
  release:
    uses: wittdennis/pipelines/.github/workflows/cog-release.yaml@d7142ea4fc5237aae7ec616148530adc3577ec7d # 2.0.23
    secrets:
      release-token: ${{ secrets.RELEASE_TOKEN }}
